version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    ignore:
      # capistrano 3 is a major API change that we're unlikely to support
      - dependency-name: capistrano
        versions:
        - ">= 3.0.0"
