name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Run RuboCop linter
      uses: reviewdog/action-rubocop@v1
      with:
        github_token: ${{ secrets.github_token }}
        rubocop_version: 0.81.0
        rubocop_extensions: rubocop-performance:1.5.2 rubocop-rails:2.5.2
        level: warning
